R2PTARGET = raw2payload
CFLAGS = -Wall -O3

CC = gcc
PPU_CC = ppu-gcc
PPU_OBJCOPY = ppu-objcopy
REMOVE = rm -f
REMOVEDIR = rm -rf

OBJDIR = .

PLOBJDIR = .

PLSRC = 	jig_payload.S \
		port1_config_descriptor.S

PLOBJ = $(PLSRC:%.S=$(PLOBJDIR)/%.o) 
PLBIN = $(PLOBJ:%.o=$(PLOBJDIR)/%.bin)
PLHEADER = $(PLBIN:%.bin=$(PLOBJDIR)/%.h)

GENDEPFLAGS = -MMD -MP -MF .depp/$(@F).d

all: deps $(R2PTARGET) payloads

deps:
	@mkdir -p .depp

$(R2PTARGET): raw2payload.c
	$(CC) $(CFLAGS) $< -o $@

payloads : $(PLOBJ) $(PLBIN) $(PLHEADER)

%.o : %.S
	$(PPU_CC) $(GENDEPFLAGS) -c $< -o $@

%.bin : %.o
	$(PPU_OBJCOPY) -O binary $< $@

%.h : %.bin
	$(PWD)/$(R2PTARGET) $< $@ $(*F)

# Target: clean project.
clean:
	$(REMOVE) $(R2PTARGET)
	$(REMOVEDIR) .depp
	$(REMOVE) $(PLSRC:%.S=$(PLOBJDIR)/%.o)
	$(REMOVE) $(PLOBJ:%.o=$(PLOBJDIR)/%.bin)
	$(REMOVE) $(PLBIN:%.bin=$(PLOBJDIR)/%.h)

-include $(wildcard .depp/*)

.PHONY: all deps payloads clean
