/* ========================
   === Select a Payload ===
   ======================== */

// This is the default PSGroove payload, in .S form courtesy of subdub and ******
// * Modified by AerialX so that it is resizable.
#include "payload_default.S"

// This is AerialX's modified payload that allows you to run apps directly from USB.
// It only uses the first USB drive plugged in. Place your app in a /PS3_GAME folder on the USB drive.
// Select the /app_home/PS3_GAME from the Game menu to launch your application.
// The files in the app folders must be structured like an unpacked .pkg file.
// (eboot.bin will not usually run without modification)
// #include "payload_apploader.S"

